ktor:
  application:
    modules:
      # modules
      - org.example.data.DatabaseModuleKt.databaseModule
      - org.example.security.SecurityModuleKt.securityModule
      - org.example.user.UserModuleKt.userModule
      # plugins
      - org.example.plugins.SessionsKt.sessions
      - org.example.plugins.AuthenticationKt.authentication
      - org.example.plugins.RateLimitKt.rateLimit
      # routing
      - org.example.RoutingKt.routing
  deployment:
    port: 8080
hs_secret: $HS_SECRET
database:
  url: $DB_URL
  username: $DB_USERNAME
  password: $DB_PASSWORD
  databaseDriver: org.postgresql.Driver